### PR TITLE
@ #94 | upgrade kubespray to v2.12.1

### LINKED ISSUE #94: should upgrade to use the latest kubespray v2.12.1
https://github.com/kubernetes-sigs/kubespray/releases/tag/v2.12.1

make sure it works with existing docs

### PR DESCRIPTION
**Pull request by hieptranquoc**
connect #94 
Result test:
```
iorad-dev                     : ok=728  changed=142  unreachable=0    failed=0   

Tuesday 18 February 2020  19:31:24 +0000 (0:00:00.030)       0:13:10.330 ****** 
=============================================================================== 
download : download_container | Download image if required ------------- 62.11s
container-engine/docker : ensure docker packages are installed --------- 45.36s
download : download_file | Download item ------------------------------- 36.15s
kubernetes/master : kubeadm | Initialize first master ------------------ 29.58s
kubernetes/preinstall : Install packages requirements ------------------ 28.91s
download : download_file | Download item ------------------------------- 27.37s
download : download_container | Download image if required ------------- 25.99s
download : download_container | Download image if required ------------- 18.01s
download : download_container | Download image if required ------------- 14.61s
download : download_container | Download image if required ------------- 14.61s
bootstrap-os : Install dbus for the hostname module -------------------- 14.18s
download : download_container | Download image if required ------------- 14.00s
download : download_container | Download image if required ------------- 13.12s
download : download_file | Download item ------------------------------- 12.90s
download : download_container | Download image if required ------------- 11.98s
download : download_container | Download image if required ------------- 11.97s
download : download_container | Download image if required ------------- 10.88s
download : download_container | Download image if required ------------- 10.71s
download : download_container | Download image if required ------------- 10.48s
download : download_file | Download item ------------------------------- 10.28s
```
Please check this PR! Thank you.

### CODE REVIEW

**Comment by hoatle** [comment]
@hieptranquoc ansible host mode did not work

```
TASK [kubernetes/master : kubeadm | Create kubeadm config] *********************
Wednesday 19 February 2020  09:19:26 +0700 (0:00:00.119)       0:06:53.448 **** 
fatal: [k8s-01]: FAILED! => {"changed": false, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ lookup('password', credentials_dir + '/kubeadm_certificate_key.creds length=64 chars=hexdigits') | lower }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'password'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unable to create local directories(/vagrant/workspace/credentials): [Errno 30] Read-only file system: '/vagrant'"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/Users/hoatle/k8s-dev/extensions/kubespray/cluster.retry

PLAY RECAP *********************************************************************
k8s-01                     : ok=566  changed=24   unreachable=0    failed=1   

Wednesday 19 February 2020  09:19:27 +0700 (0:00:00.603)       0:06:54.052 **** 
=============================================================================== 
download : download_file | Download item ------------------------------- 58.70s
download : download_file | Download item ------------------------------- 19.50s
bootstrap-os : Install dbus for the hostname module -------------------- 10.50s
download : download_file | Download item -------------------------------- 9.94s
download : download_file | Download item -------------------------------- 8.29s
download : download | Download files / images --------------------------- 6.69s
bootstrap-os : Assign inventory name to unconfigured hostnames (non-CoreOS, Suse and ClearLinux) --- 6.68s
download : download_container | Download image if required -------------- 5.73s
container-engine/docker : ensure docker packages are installed ---------- 5.52s
kubernetes/preinstall : Create kubernetes directories ------------------- 5.12s
download : download_container | Download image if required -------------- 4.85s
download : download_container | Download image if required -------------- 4.67s
bootstrap-os : Gather host facts to get ansible_os_family --------------- 3.60s
Gathering Facts --------------------------------------------------------- 3.48s
kubernetes/preinstall : Create cni directories -------------------------- 3.10s
download : download | Sync files / images from ansible host to nodes ---- 2.53s
kubernetes/preinstall : Install packages requirements ------------------- 2.45s
container-engine/docker : ensure service is started if docker packages are already present --- 2.31s
download : download | Sync files / images from ansible host to nodes ---- 2.04s
download : download | Download files / images --------------------------- 1.93s
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Review by hoatle — CHANGES_REQUESTED** [review]
@hieptranquoc make sure to test with different configs to make sure everything should work as expected.

**Comment by hieptranquoc** [comment]
@hoatle I fixed!
Guest mode:
```
k8s-01                     : ok=727  changed=153  unreachable=0    failed=0   skipped=835  rescued=0    ignored=1

Thursday 20 February 2020  01:41:40 +0700 (0:00:00.022)       0:13:02.091 ***** 
=============================================================================== 
download : download_container | Download image if required ------------- 62.11s
container-engine/docker : ensure docker packages are installed --------- 45.36s
download : download_file | Download item ------------------------------- 36.15s
kubernetes/master : kubeadm | Initialize first master ------------------ 29.58s
kubernetes/preinstall : Install packages requirements ------------------ 28.91s
download : download_file | Download item ------------------------------- 27.37s
download : download_container | Download image if required ------------- 25.99s
download : download_container | Download image if required ------------- 18.01s
download : download_container | Download image if required ------------- 14.61s
download : download_container | Download image if required ------------- 14.61s
bootstrap-os : Install dbus for the hostname module -------------------- 14.18s
download : download_container | Download image if required ------------- 14.00s
download : download_container | Download image if required ------------- 13.12s
download : download_file | Download item ------------------------------- 12.90s
download : download_container | Download image if required ------------- 11.98s
download : download_container | Download image if required ------------- 11.97s
download : download_container | Download image if required ------------- 10.88s
download : download_container | Download image if required ------------- 10.71s
download : download_container | Download image if required ------------- 10.48s
download : download_file | Download item ------------------------------- 10.28s
```

Host mode:
```
PLAY RECAP *********************************************************************
k8s-01                     : ok=704  changed=137  unreachable=0    failed=0    skipped=927  rescued=0    ignored=1   

Thursday 20 February 2020  01:52:40 +0700 (0:00:00.036)       0:13:02.091 ***** 
=============================================================================== 
kubernetes/preinstall : Install packages requirements ------------------ 74.19s
download : download_container | Download image if required ------------- 57.26s
container-engine/docker : ensure docker packages are installed --------- 47.85s
kubernetes/master : kubeadm | Initialize first master ------------------ 29.95s
download : download_file | Download item ------------------------------- 20.95s
bootstrap-os : Install dbus for the hostname module -------------------- 20.18s
download : download_container | Download image if required ------------- 17.90s
download : download_file | Download item ------------------------------- 17.36s
download : download_container | Download image if required ------------- 17.26s
download : download_container | Download image if required ------------- 13.93s
download : download_container | Download image if required ------------- 12.13s
download : download_container | Download image if required ------------- 11.98s
download : download_container | Download image if required ------------- 11.76s
container-engine/docker : ensure docker-ce repository is enabled ------- 11.04s
download : download_container | Download image if required ------------- 11.02s
download : download_container | Download image if required ------------- 10.83s
download : download_file | Download item ------------------------------- 10.62s
download : download_container | Download image if required ------------- 10.44s
download : download_container | Download image if required -------------- 9.86s
kubernetes-apps/network_plugin/flannel : Flannel | Wait for flannel subnet.env file presence --- 9.22s
```
Detail:
- Ansible 2.9 ( 2.9.5 ) is recommended to have enough plugins.
- `Credential_dir` is not run with host mode, so it will be removed from the default config.

**Comment by hoatle** [comment]
my latest check:
- 1 node with ansible guest mode: works
- 1 node with ansible host mode: works
- 3 nodes with ansible guest mode: known issue, does not work yet (#20)
- 3 nodes with ansible host mode: did not work as expected
This is my config_override.yaml file:

```yaml
teracy-dev:

  entry_location:
    git:
      remote:
        origin: git@github.com:hoatle/teracy-dev-entry-k8s.git
      branch: develop
    sync: false

  extensions:

    - _id: "entry-k8s"
      path:
        lookup: workspace
      location:
          git:
            remote:
              origin: git@github.com:hoatle/teracy-dev-k8s.git
              upstream: git@github.com:teracyhq-incubator/teracy-dev-k8s.git
            branch: develop
      enabled: true


teracy-dev-certs:
  ansible:
    mode: host


teracy-dev-k8s:
  ansible:
    verbose: v
    mode: host

  num_instances: 3
  vm_memory: 1200
  vm_cpus: 1
```

the errors after `$ vagrant up`

```
TASK [etcd : Gen_certs | run cert generation script] ***************************
Thursday 20 February 2020  13:09:31 +0700 (0:00:00.081)       0:07:36.710 ***** 
fatal: [k8s-03 -> 127.0.0.1]: FAILED! => {"changed": true, "cmd": ["bash", "-x", "/usr/local/bin/etcd-scripts/make-ssl-etcd.sh", "-f", "/etc/ssl/etcd/openssl.conf", "-d", "/etc/ssl/etcd/ssl"], "delta": "0:00:00.003778", "end": "2020-02-20 06:09:30.373905", "msg": "non-zero return code", "rc": 127, "start": "2020-02-20 06:09:30.370127", "stderr": "bash: /usr/local/bin/etcd-scripts/make-ssl-etcd.sh: No such file or directory", "stderr_lines": ["bash: /usr/local/bin/etcd-scripts/make-ssl-etcd.sh: No such file or directory"], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
k8s-01                     : ok=26   changed=7    unreachable=0    failed=1    skipped=41   rescued=0    ignored=0   
k8s-02                     : ok=24   changed=7    unreachable=0    failed=1    skipped=35   rescued=0    ignored=0   
k8s-03                     : ok=331  changed=47   unreachable=0    failed=1    skipped=277  rescued=0    ignored=0   

Thursday 20 February 2020  13:09:31 +0700 (0:00:00.174)       0:07:36.885 ***** 
=============================================================================== 
download : download_file | Download item ------------------------------- 59.70s
kubernetes/preinstall : Install packages requirements ------------------ 49.50s
download : download_container | Download image if required ------------- 45.32s
bootstrap-os : Install dbus for the hostname module -------------------- 42.98s
container-engine/docker : ensure docker packages are installed --------- 35.13s
download : download_file | Download item ------------------------------- 18.39s
download : download_container | Download image if required ------------- 16.85s
download : download_container | Download image if required ------------- 14.09s
download : download_container | Download image if required ------------- 11.88s
download : download_container | Download image if required ------------- 10.52s
container-engine/docker : ensure docker-ce repository is enabled ------- 10.51s
download : download_container | Download image if required -------------- 8.88s
download : download_container | Download image if required -------------- 8.78s
download : download_container | Download image if required -------------- 7.98s
download : download_container | Download image if required -------------- 7.41s
download : download_file | Download item -------------------------------- 7.39s
download : download_container | Download image if required -------------- 2.70s
download : download | Download files / images --------------------------- 1.68s
bootstrap-os : Fetch /etc/os-release ------------------------------------ 1.53s
container-engine/docker : ensure docker-ce repository public key is installed --- 1.42s
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

@hieptranquoc please check and fix this.

**Comment by hieptranquoc** [comment]
@hoatle Your mistake! Not me. Your config is wrong. Please check again.

**Comment by hoatle** [comment]
@hieptranquoc then please show me the right config.

**Comment by hoatle** [comment]
ok, so the update the config above with `vm_memory: 1600` and it works:

```
PLAY RECAP *********************************************************************
k8s-01                     : ok=734  changed=106  unreachable=0    failed=0    skipped=948  rescued=0    ignored=1   
k8s-02                     : ok=632  changed=87   unreachable=0    failed=0    skipped=820  rescued=0    ignored=1   
k8s-03                     : ok=484  changed=59   unreachable=0    failed=0    skipped=561  rescued=0    ignored=1   

Friday 21 February 2020  04:09:04 +0700 (0:00:00.113)       0:19:47.016 ******* 
=============================================================================== 
download : download_file | Download item ------------------------------ 157.15s
download : download_container | Download image if required ------------ 111.23s
download : download_file | Download item ------------------------------- 53.71s
download : download_container | Download image if required ------------- 35.07s
download : download_container | Download image if required ------------- 34.33s
kubernetes/master : kubeadm | Init other uninitialized masters --------- 32.67s
kubernetes/master : kubeadm | Initialize first master ------------------ 30.99s
kubernetes/kubeadm : Join to cluster ----------------------------------- 27.27s
download : download_container | Download image if required ------------- 18.87s
download : download_container | Download image if required ------------- 18.12s
download : download_container | Download image if required ------------- 16.92s
download : download_container | Download image if required ------------- 16.00s
download : download_container | Download image if required ------------- 15.59s
download : download_file | Download item ------------------------------- 14.91s
download : download_file | Download item ------------------------------- 14.82s
download : download_container | Download image if required ------------- 13.96s
etcd : reload etcd ----------------------------------------------------- 10.84s
download : download_container | Download image if required ------------- 10.44s
download : download_container | Download image if required -------------- 9.73s
kubernetes-apps/helm : Helm | Install client on all masters ------------- 9.60s
==> k8s-03: Running provisioner: Display IP (shell)...
    k8s-03: Running: script: Display IP
    k8s-03: IP Address: 172.17.8.103
==> k8s-03: Running provisioner: guest-hosts-fixer (shell)...
    k8s-03: Running: inline script
```

```
macbook-pro:artifacts hoatle$ kubectl get node
NAME     STATUS   ROLES    AGE     VERSION
k8s-01   Ready    master   5m51s   v1.16.7
k8s-02   Ready    master   5m6s    v1.16.7
k8s-03   Ready    <none>   3m51s   v1.16.7
macbook-pro:artifacts hoatle$ kubectl cluster-info 
Kubernetes master is running at https://172.17.8.101:6443
coredns is running at https://172.17.8.101:6443/api/v1/namespaces/kube-system/services/coredns:dns/proxy
kubernetes-dashboard is running at https://172.17.8.101:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
metrics-server is running at https://172.17.8.101:6443/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

**Review by hoatle — APPROVED** [review]
LGTM, thank you.

**Pull request merged**
